//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EA() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZumNet.Web.Resources.EA", typeof(EA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Approval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxApproval {
            get {
                return ResourceManager.GetString("BoxApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Assigned과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxAssigned {
            get {
                return ResourceManager.GetString("BoxAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxCompleted {
            get {
                return ResourceManager.GetString("BoxCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distributed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxDistribued {
            get {
                return ResourceManager.GetString("BoxDistribued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxExpected {
            get {
                return ResourceManager.GetString("BoxExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxInProcess {
            get {
                return ResourceManager.GetString("BoxInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxReceived {
            get {
                return ResourceManager.GetString("BoxReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxReference {
            get {
                return ResourceManager.GetString("BoxReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returned과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxReturn {
            get {
                return ResourceManager.GetString("BoxReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxSaved {
            get {
                return ResourceManager.GetString("BoxSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxSent {
            get {
                return ResourceManager.GetString("BoxSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shared Folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxShared {
            get {
                return ResourceManager.GetString("BoxShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submitted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxSubmitted {
            get {
                return ResourceManager.GetString("BoxSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Approve과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxToApprove {
            get {
                return ResourceManager.GetString("BoxToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check First과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxToConfirm {
            get {
                return ResourceManager.GetString("BoxToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To Do과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxToDo {
            get {
                return ResourceManager.GetString("BoxToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Later과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxViewLater {
            get {
                return ResourceManager.GetString("BoxViewLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxWaiting {
            get {
                return ResourceManager.GetString("BoxWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BoxWithdraw {
            get {
                return ResourceManager.GetString("BoxWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Approval Line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PersonLine {
            get {
                return ResourceManager.GetString("PersonLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_Authorize {
            get {
                return ResourceManager.GetString("SK_Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_ByPass {
            get {
                return ResourceManager.GetString("SK_ByPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direct과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_Direct {
            get {
                return ResourceManager.GetString("SK_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_Normal {
            get {
                return ResourceManager.GetString("SK_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Later과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_Post {
            get {
                return ResourceManager.GetString("SK_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beforehand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_Pre {
            get {
                return ResourceManager.GetString("SK_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Substitue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SK_Substitue {
            get {
                return ResourceManager.GetString("SK_Substitue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Approval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Approval {
            get {
                return ResourceManager.GetString("SS_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Back {
            get {
                return ResourceManager.GetString("SS_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Cancel {
            get {
                return ResourceManager.GetString("SS_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Confirmed {
            get {
                return ResourceManager.GetString("SS_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disagree과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Disagree {
            get {
                return ResourceManager.GetString("SS_Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_None {
            get {
                return ResourceManager.GetString("SS_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Reject {
            get {
                return ResourceManager.GetString("SS_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserve과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Reserve {
            get {
                return ResourceManager.GetString("SS_Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Transfer {
            get {
                return ResourceManager.GetString("SS_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SS_Withdraw {
            get {
                return ResourceManager.GetString("SS_Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WS_Completed {
            get {
                return ResourceManager.GetString("WS_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WS_Error {
            get {
                return ResourceManager.GetString("WS_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In active과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WS_InActive {
            get {
                return ResourceManager.GetString("WS_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In progress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WS_InProgress {
            get {
                return ResourceManager.GetString("WS_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WS_Pending {
            get {
                return ResourceManager.GetString("WS_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progressing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WS_Progressing {
            get {
                return ResourceManager.GetString("WS_Progressing", resourceCulture);
            }
        }
    }
}
