//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZumNet.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more accounts exist. Please contact the administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_DoubleAccount {
            get {
                return ResourceManager.GetString("Auth_DoubleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong ID or password, or access through the wrong path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_Fail {
            get {
                return ResourceManager.GetString("Auth_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid login attempt.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_Fault {
            get {
                return ResourceManager.GetString("Auth_Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NoDB {
            get {
                return ResourceManager.GetString("Auth_NoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NoPermission {
            get {
                return ResourceManager.GetString("Auth_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No user information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NoUser {
            get {
                return ResourceManager.GetString("Auth_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The service has been stopped. Please contact the administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_SysDown {
            get {
                return ResourceManager.GetString("Auth_SysDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage has been suspended. Please contact the administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_UseStop {
            get {
                return ResourceManager.GetString("Auth_UseStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find a phone number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindPhoneNum {
            get {
                return ResourceManager.GetString("FindPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LangSet {
            get {
                return ResourceManager.GetString("LangSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoginId {
            get {
                return ResourceManager.GetString("LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MgtTool {
            get {
                return ResourceManager.GetString("MgtTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Organization Mgr과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OrganMgr {
            get {
                return ResourceManager.GetString("OrganMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working Condition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorkCond {
            get {
                return ResourceManager.GetString("WorkCond", resourceCulture);
            }
        }
    }
}
