//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZumNet.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// 리소스이름으로 가져오기
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public static string Get(string name) {
            return ResourceManager.GetString(name, resourceCulture);
        }

        /// <summary>
        ///   Access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessRights {
            get {
                return ResourceManager.GetString("AccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AdminTool {
            get {
                return ResourceManager.GetString("AdminTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attach과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attachments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AttendWork {
            get {
                return ResourceManager.GetString("AttendWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already logged in user.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_AlreadyLogin {
            get {
                return ResourceManager.GetString("Auth_AlreadyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more accounts exist. Please contact the administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_DoubleAccount {
            get {
                return ResourceManager.GetString("Auth_DoubleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong ID or password, or access through the wrong path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_Fail {
            get {
                return ResourceManager.GetString("Auth_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid login attempt.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_Fault {
            get {
                return ResourceManager.GetString("Auth_Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid path access.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_InvalidPath {
            get {
                return ResourceManager.GetString("Auth_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NoDB {
            get {
                return ResourceManager.GetString("Auth_NoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NoPermission {
            get {
                return ResourceManager.GetString("Auth_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No user information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NoUser {
            get {
                return ResourceManager.GetString("Auth_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The service has been stopped. Please contact the administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_SysDown {
            get {
                return ResourceManager.GetString("Auth_SysDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage has been suspended. Please contact the administrator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_UseStop {
            get {
                return ResourceManager.GetString("Auth_UseStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch processing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BatchProcess {
            get {
                return ResourceManager.GetString("BatchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulletin Board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BBoard {
            get {
                return ResourceManager.GetString("BBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calendar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compose과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Compose {
            get {
                return ResourceManager.GetString("Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Document과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeDoc {
            get {
                return ResourceManager.GetString("ComposeDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Form과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeForm {
            get {
                return ResourceManager.GetString("ComposeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Knowledge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeKnowledge {
            get {
                return ResourceManager.GetString("ComposeKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeLog {
            get {
                return ResourceManager.GetString("ComposeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compose과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeNew {
            get {
                return ResourceManager.GetString("ComposeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeSchedule {
            get {
                return ResourceManager.GetString("ComposeSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Task과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ComposeTask {
            get {
                return ResourceManager.GetString("ComposeTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cresyn과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cresyn {
            get {
                return ResourceManager.GetString("Cresyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Approved과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Approve {
            get {
                return ResourceManager.GetString("Date_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Complete {
            get {
                return ResourceManager.GetString("Date_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Confirm {
            get {
                return ResourceManager.GetString("Date_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Created {
            get {
                return ResourceManager.GetString("Date_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Deleted {
            get {
                return ResourceManager.GetString("Date_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drafted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Draft {
            get {
                return ResourceManager.GetString("Date_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Edit {
            get {
                return ResourceManager.GetString("Date_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_End {
            get {
                return ResourceManager.GetString("Date_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expiration date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Expired {
            get {
                return ResourceManager.GetString("Date_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Modify {
            get {
                return ResourceManager.GetString("Date_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pop-up date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Popup {
            get {
                return ResourceManager.GetString("Date_Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Posted date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Posted {
            get {
                return ResourceManager.GetString("Date_Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Receipt {
            get {
                return ResourceManager.GetString("Date_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Receive {
            get {
                return ResourceManager.GetString("Date_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Regist {
            get {
                return ResourceManager.GetString("Date_Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Request {
            get {
                return ResourceManager.GetString("Date_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Return {
            get {
                return ResourceManager.GetString("Date_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Send {
            get {
                return ResourceManager.GetString("Date_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Sent {
            get {
                return ResourceManager.GetString("Date_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Start {
            get {
                return ResourceManager.GetString("Date_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_View {
            get {
                return ResourceManager.GetString("Date_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Date_Withdraw {
            get {
                return ResourceManager.GetString("Date_Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Department과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Division과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doc Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditorExpand {
            get {
                return ResourceManager.GetString("EditorExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fold Editor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EditorFold {
            get {
                return ResourceManager.GetString("EditorFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File extension과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileExt {
            get {
                return ResourceManager.GetString("FileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find a phone number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindPhoneNum {
            get {
                return ResourceManager.GetString("FindPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string First2 {
            get {
                return ResourceManager.GetString("First2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folding과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Folding {
            get {
                return ResourceManager.GetString("Folding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GotoWork {
            get {
                return ResourceManager.GetString("GotoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Groupware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Groupware {
            get {
                return ResourceManager.GetString("Groupware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Important과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Business trip과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InBiz {
            get {
                return ResourceManager.GetString("InBiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InOffWork {
            get {
                return ResourceManager.GetString("InOffWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outside work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InOut {
            get {
                return ResourceManager.GetString("InOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In rest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InRest {
            get {
                return ResourceManager.GetString("InRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In training과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InTraining {
            get {
                return ResourceManager.GetString("InTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In working과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InWork {
            get {
                return ResourceManager.GetString("InWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Jikchaek {
            get {
                return ResourceManager.GetString("Jikchaek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Jikwi {
            get {
                return ResourceManager.GetString("Jikwi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knowledge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Knowledge {
            get {
                return ResourceManager.GetString("Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LangSet {
            get {
                return ResourceManager.GetString("LangSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Last2 {
            get {
                return ResourceManager.GetString("Last2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leave Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LeaveTime {
            get {
                return ResourceManager.GetString("LeaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LeaveWork {
            get {
                return ResourceManager.GetString("LeaveWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ListCount {
            get {
                return ResourceManager.GetString("ListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoginId {
            get {
                return ResourceManager.GetString("LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask as read과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaskRead {
            get {
                return ResourceManager.GetString("MaskRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mask as unread과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MaskUnRead {
            get {
                return ResourceManager.GetString("MaskUnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No items to show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoItemShow {
            get {
                return ResourceManager.GetString("NoItemShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OffWork {
            get {
                return ResourceManager.GetString("OffWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Off Work Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OffWorkCancel {
            get {
                return ResourceManager.GetString("OffWorkCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Organization Chart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OrganChart {
            get {
                return ResourceManager.GetString("OrganChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Organization Mgr과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OrganMgr {
            get {
                return ResourceManager.GetString("OrganMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password_Change {
            get {
                return ResourceManager.GetString("Password_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New password confirmation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password_Confirm {
            get {
                return ResourceManager.GetString("Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password_Current {
            get {
                return ResourceManager.GetString("Password_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password_New {
            get {
                return ResourceManager.GetString("Password_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Planned Leave과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PlanLeaveTime {
            get {
                return ResourceManager.GetString("PlanLeaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Planned Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PlanWorktTime {
            get {
                return ResourceManager.GetString("PlanWorktTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pop-Up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Popup {
            get {
                return ResourceManager.GetString("Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Portal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Posting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Posting {
            get {
                return ResourceManager.GetString("Posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PrevWork {
            get {
                return ResourceManager.GetString("PrevWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Document과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecentDocs {
            get {
                return ResourceManager.GetString("RecentDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Knowledge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecentKnowledges {
            get {
                return ResourceManager.GetString("RecentKnowledges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Notices과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecentNotice {
            get {
                return ResourceManager.GetString("RecentNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Posts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RecentPosts {
            get {
                return ResourceManager.GetString("RecentPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplyWrite {
            get {
                return ResourceManager.GetString("ReplyWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request Dept.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReqDept {
            get {
                return ResourceManager.GetString("ReqDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requester과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Requester {
            get {
                return ResourceManager.GetString("Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seq.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SeqNo {
            get {
                return ResourceManager.GetString("SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TaskLog {
            get {
                return ResourceManager.GetString("TaskLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temporary Box과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempBox {
            get {
                return ResourceManager.GetString("TempBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp Box과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempBox2 {
            get {
                return ResourceManager.GetString("TempBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temporary save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TempSave {
            get {
                return ResourceManager.GetString("TempSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To-do Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TodoTransfer {
            get {
                return ResourceManager.GetString("TodoTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Untitled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filer Uploader과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Uploader {
            get {
                return ResourceManager.GetString("Uploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand Uploader과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UploaderExpand {
            get {
                return ResourceManager.GetString("UploaderExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fold Uploader과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UploaderFold {
            get {
                return ResourceManager.GetString("UploaderFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Views과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorkCond {
            get {
                return ResourceManager.GetString("WorkCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total per month과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorkMonthTotal {
            get {
                return ResourceManager.GetString("WorkMonthTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work today과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorkToday {
            get {
                return ResourceManager.GetString("WorkToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorktTime {
            get {
                return ResourceManager.GetString("WorktTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avg. per week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WorkWeekAvg {
            get {
                return ResourceManager.GetString("WorkWeekAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing Dept.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WriteDept {
            get {
                return ResourceManager.GetString("WriteDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
    }
}
