//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZumNet.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lbl_LoginId {
            get {
                return ResourceManager.GetString("lbl_LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lbl_RememberMe {
            get {
                return ResourceManager.GetString("lbl_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정이 하나 이상 존재 합니다. 관리자에게 문의 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_DBLACCOUNT {
            get {
                return ResourceManager.GetString("msg_Auth_DBLACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디나 암호가 틀렸거나 잘못된 경로로 접근했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_FAIL {
            get {
                return ResourceManager.GetString("msg_Auth_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 로그인 시도입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_FAULT {
            get {
                return ResourceManager.GetString("msg_Auth_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용이 일시 정지 되었습니다. 관리자에게 문의 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_NOACT {
            get {
                return ResourceManager.GetString("msg_Auth_NOACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   권한이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_NOAUTH {
            get {
                return ResourceManager.GetString("msg_Auth_NOAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존재하지 않는 아이디입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_NODB {
            get {
                return ResourceManager.GetString("msg_Auth_NODB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 정보가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_NOUSER {
            get {
                return ResourceManager.GetString("msg_Auth_NOUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서비스가 정지 되었습니다. 관리자에게 문의 바랍니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_Auth_SYSDOWN {
            get {
                return ResourceManager.GetString("msg_Auth_SYSDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ttl_Login {
            get {
                return ResourceManager.GetString("ttl_Login", resourceCulture);
            }
        }
    }
}
